quarkus:
  http:
    port: 8080
    read-timeout: 10S
  banner:
    enabled: false

  shutdown:
    timeout: 10

  #DB Config
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_SCHEMA:db_quarkus}?stringtype=unspecified
    username: ${DB_USER:root}
    password: ${DB_PWD:root}
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
    database:
      generation: none
  liquibase:
    migrate-at-start: true
    change-log: liquibase/migrations.yaml


  #Logging
  log:
    level: INFO
    console:
      color: true
      format: "{\"level\": \"%p\", \"at\": \"%d{yyyy-MM-dd'T'HH:mm:ssZ}\", \"class\": \"%C\", \"message\": \"%s\", \"error\": \"%e\"}%n"
    category:
      "io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator":
        level: TRACE
      "liquibase":
        level: WARN


  #Swagger UI & OpenAPI
  smallrye-openapi:
    path: /docs
    enable: ${ENABLE_OPENAPI:true}
  swagger-ui:
    title: Quarkus API Docs
    path: /api-docs
    theme: original
    enable: ${ENABLE_OPENAPI:true}

smallrye:
  jwt:
    sign:
      key-location: ${JWT_PRIVATE_KEY_PATH:keys/private_key.pem}
    verify:
      key:
        location: ${JWT_PUBLIC_KEY_PATH:keys/public_key.pem}
        key-format: PEM_KEY
    new-token:
      issuer: ${APP_JWT_ISSUER:https://quarkus.io}
      lifespan: ${APP_JWT_EXP_SECONDS:900}

#Microprofile Configs, - OpenAPI, JWT
mp:
  jwt:
    verify:
      publickey:
        location: ${JWT_PUBLIC_KEY_PATH:keys/public_key.pem}
      issuer: ${JWT_ISSUER:https://quarkus.io}
  openapi:
    extensions:
      smallrye:
        info:
          title: Quarkus API

